### ISSUE TITLE
[Suggestion] Alternate system of seasons for tropical biomes

### ISSUE THREAD

**Issue by Sunconure11** [lucaargolo/fabric-seasons#1]
Since it obviously does not snow in say, a jungle, are there any plans to make it so tropical biomes don’t follow the same season layout as temperate and cold biomes? Even ones from other mods? I will admit I haven’t gotten to touching this mod yet, as GDLauncher was acting weird for a bit.

**Comment by lucaargolo** [comment]
They already don't, neither swamps nor jungles nor deserts have snow in the winter, their temperatures change a little, and foliage color may vary but in the end, they stay mostly the same between all seasons.
