### ISSUE TITLE
Conflict with chipped decorative ice cubes

### ISSUE THREAD

**Issue by AltoClef6115** [lucaargolo/fabric-seasons#100]
Using this mod will cause a lot of texture errors in the ice cubes in the chipped mod, and the ice cube item name in the chipped mod will be changed to seasonal_ice

**Comment by xR4YM0ND** [comment]
Same here ... all ice tags not working
Fabric 1.19.2

https://github.com/terrarium-earth/Chipped/issues/179

**Comment by xR4YM0ND** [comment]
Fresh latest.log https://gist.github.com/SpigotDE/e98cee3264cea6bfbafb60c3618134a6

Its too long ( 21606 lines ) actually

**Comment by lucaargolo** [comment]
This should be fixed as of version 2.0.

**Comment by xR4YM0ND** [comment]
Yes
