### ISSUE TITLE
The seasonal snow layer drops wrong item when shovelled

### ISSUE THREAD

**Issue by WarmIceCream** [lucaargolo/fabric-seasons#102]
The snow layer this mod adds drops a snow _block_ instead of the expected snow _ball_ when broken with a shovel (only tried shovelling with a wooden shovel, but I don't imagine it's different with other shovels)

edit: I am in a snowy tiaga biome, though I've also not tested if that would make any difference

**Comment by lucaargolo** [comment]
This should be fixed as of version 2.0.
