### ISSUE TITLE
Crashes on game launch

### ISSUE THREAD

**Issue by Quinn-TM** [lucaargolo/fabric-seasons#103]
I'm not super literate with this kinda stuff, but from reading the logs my best guess is that the issue is related to lithium somehow? 
[latest.log](https://github.com/lucaargolo/fabric-seasons/files/10914419/latest.log)

**Comment by Cirvel** [comment]
It is related to Lithium, probably due to the removal of vanilla temperature caching, try downgrading it to version 0.10.4.

**Comment by lucaargolo** [comment]
Heyy, I'm closing this since I wasn't able to reproduce it with the 2.0 version of the mod, and the newest Lithium release. I actually changed a few parts of the code related to biome temperature, so maybe it got indirectly fixed. If this issue happens again feel free to reopen the issue.
