### ISSUE TITLE
Lost Greenhouse Glass on latest update

### ISSUE THREAD

**Issue by Zarepheth** [lucaargolo/fabric-seasons#106]
I just updated to Version 2.0. (fabric-seasons-2.0+1.19.jar). After leaving the Twilight Forest dimension and returning to my base, I noticed a distinct lack of Greenhouse Glass over my fields.

Was this intended?
Is it a mod conflict?
Did they just lose their texture and turn invisible. (I haven't yet tried to walk into or place anything where they were.)

**Comment by Zarepheth** [comment]
Just checked - greenhouse glass is gone from the world. It is also missing from JEI.

I also updated Item Obliterator today, from 1.1.0 to 1.2.0. Their change log only indicates some additional options in the config file. The modpack's author has blacklisted 6 items, none from Fabric Seasons.

**Comment by lucaargolo** [comment]
That's intended. Blocks and items from the mod have been moved to [Fabric Seasons: Extras](https://github.com/lucaargolo/fabric-seasons-extras), to allow the main mod to have independent client and server components. The addon hasn't yet been approved by CurseForge/Modrinth but you can get the most recent jar [here](https://github.com/lucaargolo/fabric-seasons-extras/releases/download/1.0-BETA%2B1.19/fabric-seasons-extras-1.0-BETA+1.19.jar)

**Comment by Zarepheth** [comment]
That is something that should have been present in the CurseForge change log - with extra emphasis!

I'll check out the jar file and manually add it to my profile.

**Comment by lucaargolo** [comment]
Yeah, but Curseforge decided to approve the 2.0 update and not approve the extras addon and the compatibility packs, so I'm still waiting to properly announce and release the update. I'll write a temporary message in the changelogs tho.
