### ISSUE TITLE
Prompts for extras every world load with no config option to disable

### ISSUE THREAD

**Issue by sisby-folk** [lucaargolo/fabric-seasons#107]
Hey! it seems like there's an issue in the latest version of seasons where the "once only" message happens every world load.

Secondarily, as a modpack dev it'd be helpful to have the "already shown notification" status stored in the config, so we can set it by default so modpack players don't send us bug reports about it.

**Comment by lucaargolo** [comment]
Heyy! After you load the game for the first time, a file will appear in your .minecraft/data folder. You can ship that file with your modpack and the message won't show for new players!

**Comment by sisby-folk** [comment]
Hello again! This doesn't work if the folder `.minecraft/data` doesn't already exist. That is to say, normal minecraft installs will see this issue message occur every single load, as indicated.

To fix this, just make the `.minecraft/data` dir [here](https://github.com/lucaargolo/fabric-seasons/blob/383316538ce1f737a57d6d8981b0d8b9d2ebef65/src/main/java/io/github/lucaargolo/seasons/utils/CompatWarnState.java#L55) using `compatWarnFile.getParentFile().mkdirs()`
