### ISSUE TITLE
2.0 conflict with snow! real magic?

### ISSUE THREAD

**Issue by sisby-folk** [lucaargolo/fabric-seasons#108]
This one's from a modpack user, so I only know it occurred with snow real magic on 2.0 and that's about it.

[crash-2023-04-19_11.42.32-server.txt](https://github.com/lucaargolo/fabric-seasons/files/11278893/crash-2023-04-19_11.42.32-server.txt)

**Comment by Cape-City** [comment]
Hi, Snownee has fixed this issue here:

https://github.com/Snownee/SnowRealMagic/issues/282

But only for 1.19.2 and 1.19.4 - 1.19.3 is no longer maintained. Will Seasons adress this issue in 1.19.3?

**Comment by Cape-City** [comment]
Also the latest version of seasons

fabric-seasons-2.1+1.19.3.jar
fabric-seasons-extras-1.2-BETA+1.19.3.jar

are incompat with the latest 1.19.3 version of the snow magic mod. game is still crashing, while loading up the world.

[crash-2023-05-12_09.58.23-server.txt](https://github.com/lucaargolo/fabric-seasons/files/11460794/crash-2023-05-12_09.58.23-server.txt)

[latest.log](https://github.com/lucaargolo/fabric-seasons/files/11460796/latest.log)

**Comment by Cape-City** [comment]
The latest update fabric-seasons-2.2+1.19.3.jar still has this incompat issue with SnowRealMagic :(

[crash-2023-05-24_21.59.25-server.txt](https://github.com/lucaargolo/fabric-seasons/files/11558604/crash-2023-05-24_21.59.25-server.txt)

[latest.log](https://github.com/lucaargolo/fabric-seasons/files/11558608/latest.log)

**Comment by lucaargolo** [comment]
This is already fixed on 1.19.2, 1.19.4 and 1.20.1. Unfortunately, since the snow real magic mod is not maintained in 1.19.3 I can't do anything about it.
