### ISSUE TITLE
Update 2.0 breaks oceans, lakes and rivers LOL BE AWARED OF THIS MATES

### ISSUE THREAD

**Issue by nizeyoral** [lucaargolo/fabric-seasons#109]
Reaching the winter causing a weird bug where the water freezes, turns into ice BUT THEN the ice blocks disappearing completely. Like they disappearing and not smelting. Now my rivers etc missing the first water block row lol.
LUCKELY I did a backup before loaded my world lol.

I just downgraded the mod to previous build and now everything is working.

**Mods im using:**

Just Enough Items (JEI)
mezz
jei-1.19.2-fabric-11.6.0.1015.jar

libIPN
mirinimi
libIPN-fabric-1.19-2.0.4.jar

Naturalist
Starfish_Studios
naturalist-fabric-3.0.1-1.19.2.jar

Nyf's Spiders
theNyfaria
spiderstpo-fabric-1.19.2-2.0.3.jar

RightClickHarvest
jamalam360
right-click-harvest-3.1.0+1.19-1.19.2.jar

Sodium
jellysquid3_
sodium-fabric-mc1.19.2-0.4.4+build.18.jar

ToolTipFix
Kyrptonaught
tooltipfix-1.1.1-1.19.jar

Traveler's Backpack [Fabric]
Tiviacz1337
travelers-backpack-1.19.2-8.2.18.jar

Vanilla Hammers
Draylar1
vanilla-hammers-3.5.0-1.19.2.jar

Xaero's Minimap
xaero96
Xaeros_Minimap_23.3.3_Fabric_1.19.1.jar

Xaero's World Map
xaero96
XaerosWorldMap_1.29.5_Fabric_1.19.1.jar

**Comment by lucaargolo** [comment]
Did the ice disappear during gameplay or after you updated the mod?

**Comment by nizeyoral** [comment]
Just tested it. Its disappearing after updating it.

**Comment by lucaargolo** [comment]
I see... Well, this is not a bug, the old version had custom blocks for the meltable ice and snow, and the new version just modifies the vanilla ones, so all Ice and Snow generated in the old version will vanish when updating to the new version. I'll try to work on a tool that automatically replaces the old ice and snow with the new ones, but for now, it's recommended that you only update worlds that are not in the winter.

**Comment by lucaargolo** [comment]
Can you try updating your world with [this mod](https://cdn.discordapp.com/attachments/725849484139036674/1098749841875664987/fabric-seasons-extras-1.1-BETA1.19.jar) also installed? Old snow and ice should not disappear, and they should be slowly replaced by newer variants.

**Comment by nizeyoral** [comment]
Youre a pro, mate. Seems to work fine here, thanks :3

**Comment by sisby-folk** [comment]
Can the datafix in that custom build be added to the mod proper for at least one fully released version of fabric seasons itself (not extras)? I can see its stand-in blocks that change to the minecraft variants on (I assume) random ticks 

![image](https://user-images.githubusercontent.com/55819817/236112926-9fe6bf73-e52c-48a7-916b-485e2df15769.png)

**Comment by GodsTitan** [comment]
Were you updating to version 1.20 from 1.19? And if so, will 1.19 still receive updates?
