### ISSUE TITLE
Custom Crop Config get reset

### ISSUE THREAD

**Issue by MokkaCicc** [lucaargolo/fabric-seasons#11]
Each time I add a custom crop config, either with the GUI or the config file. It will be reset and erase.

**Comment by lucaargolo** [comment]
That's a known issue with the config lib I'm using (AutoConfig). I already reported it to the dev but I don't know if it's fixed or not. Either way, I'll be replacing it soon™️. For now, you can modify this stuff directly in the file.

**Comment by CrossWayIstaken** [comment]
> 
> 
> That's a known issue with the config lib I'm using (AutoConfig). I already reported it to the dev but I don't know if it's fixed or not. Either way, I'll be replacing it soontm. For now, you can modify this stuff directly in the file.

Can you please give a hint how? I just can't figure it out, something like an example config would be nice.

**Comment by lucaargolo** [comment]
![image](https://user-images.githubusercontent.com/49497195/111035801-d4315e80-83fa-11eb-9969-e574ce5a3980.png)
This is the format you're supposed to use, you can get the crop identifier by looking at an in-game crop with the F3 debug hud opened and checking for the block you're looking at. It also works for modded crops.

**Comment by CrossWayIstaken** [comment]
Thanks!

**Comment by lucaargolo** [comment]
Unfortunately, the AutoConfig dev never fixed this bug so I just removed it. I'll be moving to a new system in the future but for now, the config screen is disabled.
