### ISSUE TITLE
Mod seems incompatible with Snow! Real Magic! Mod

### ISSUE THREAD

**Issue by Cape-City** [lucaargolo/fabric-seasons#112]
I'm using 1.19.3 on fabric, to test this mod i jumped forward many time 30 days (/time add 30d).
If i do this for a couple of time and then start the rain (/weather rain) and jumped again 30d further,
the game crashed. If i do exakt the same without this mod, the game did not crash. I figured out, that there
seems an incompability with the Snow! Real Magic! Mod.

Fabric API
modmuss50
fabric-api-0.76.1+1.19.3.jar

Fabric Seasons
D4rkness_King
fabric-seasons-2.0+1.19.3.jar

Fabric Seasons: Extras
D4rkness_King
fabric-seasons-extras-1.1-BETA+1.19.3.jar

Kiwi 🥝 (Fabric)
Snownee_
Kiwi-1.19.3-fabric-9.1.1.jar

Snow! Real Magic! ⛄ (Fabric)
Snownee_
SnowRealMagic-1.19.3-fabric-7.4.0.jar

[crash-2023-04-22_17.42.06-server.txt](https://github.com/lucaargolo/fabric-seasons/files/11301689/crash-2023-04-22_17.42.06-server.txt)

[latest.log](https://github.com/lucaargolo/fabric-seasons/files/11301690/latest.log)

**Comment by lucaargolo** [comment]
Thanks for the extra info but this issue is the same as #108
