### ISSUE TITLE
Crash: Incompatibility with Sodium 0.4.11

### ISSUE THREAD

**Issue by muhammedesadcomert** [lucaargolo/fabric-seasons#116]
Game crashes on startup if Sodium 0.4.11 is installed.

Uninstalling Sodium or Fabric Seasons will allow the game to load properly. Also, Fabric Seasons works properly with `Sodium 0.4.10+build.24`

Same as #115, I just wanted to open the issue under a more meaningful title.

Logs: https://mclo.gs/t9Z419N

Minecraft version: `1.19.4`

Mods:
```
Fabric API: 0.78.0
Fabric Seasons: 2.0.1
Mod Menu: 6.1.0-rc.4
Sodium: 0.4.11+build.26
```

**Comment by vico93** [comment]
I second this. Needed to remove both Seasons and Seasons: Extras to the game to work

**Comment by joeyak** [comment]
Close the ticket #115 since this one was more clear. Can confirm it works after downgrading sodium
