### ISSUE TITLE
System Time Crash

### ISSUE THREAD

**Issue by ZeburaBlack** [lucaargolo/fabric-seasons#13]
[crash-2021-03-11_20.05.33-client.txt](https://github.com/lucaargolo/fabric-seasons/files/6127336/crash-2021-03-11_20.05.33-client.txt)

Seems to be a conflict with Canvas, but having config set to system time causes crash on title screen load.

**Comment by lucaargolo** [comment]
Hey sorry about that, it should be fixed in 1.1.1-BETA
