### ISSUE TITLE
Ice doesn't melt outside of winter

### ISSUE THREAD

**Issue by Peerius1701** [lucaargolo/fabric-seasons#133]
During the season winter, ice starts to generate for example in rivers. However, as said in the title, it appears that the ice doesn't melt during other seasons. This issue occured both on a server and in singleplayer. I also looked at the config files for fabric seasons but didn't find a configuration which would explain this behavior.

I used the mod inside the Better MC v18.5 modpack, but I'm pretty sure that this mod is the cause for that.

Would love to see this issue being removed, ty in advance :)

**Comment by maisma2** [comment]
Yeah, same modpack. I have a frozen river that I gave up manually trying to break the ice for middle of the summer in the rain forest.

**Comment by xamy9000** [comment]
Yeah it's a real bummer.
Been thinking of learning java real quick to try to fix it, but I'm on vacation x)

**Comment by jmbullet** [comment]
I'm having the same problem on Better MC version 1.19.2. It bugged me so much that I went into creative mode to fly around and use the fill command to replace all ice blocks with water, but it's not a fix.

**Comment by lucaargolo** [comment]
If you have this issue, please update the mod to version 2.3, regenerate your config file, and set `shouldIceNearWaterMelt` to true.
