### ISSUE TITLE
Ice won't melt & '/season query' not working correctly

### ISSUE THREAD

**Issue by washhtubs** [lucaargolo/fabric-seasons#138]
Ice generated during winter and ice placed by a player during any season don't melt in any season unless a light source is placed near them. This also applies to snow layers that are generated by the mod. However, snow and ice that were already in the world are melted correctly (until they are replaced with snow/ice generated by the mod).

I am running the mod on a 1.19.4 Fabric server and I haven't changed any of the config files, but I ran the mod in a single player 1.19.4 Fabric world and it worked as expected so maybe it's a mod incompatibility.

There aren't any console logs I can send, but I will send the server mod list:

architectury-8.1.87-fabric.jar
audioplayer-1.19.4-1.5.2.jar
badpackets-fabric-0.4.1.jar
BlueMap-3.14-fabric-1.19.4.jar
carpet-extra-1.19.4-1.4.100.jar 
cloth-config-10.0.96-fabric.jar
collective-1.19.4-6.57.jar
fabric-api-0.83.0+1.19.4.jar 
fabric-carpet-1.19.4-1.4.101+v230319.jar
fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar
fabric-seasons-2.2.1+1.19.4.jar
ferritecore-5.2.0-fabric.jar 
floodgate-fabric.jar
Geyser-Fabric.jar 
image2map-0.4.1.jar
indium-1.0.18+mc1.19.4.jar
lazydfu-0.1.3.jar
lithium-fabric-mc1.19.4-0.11.1.jar
memoryleakfix-fabric-1.17+-1.1.1.jar
mysql-jdbc-8.0.33+20230506-all.jar
passiveendermen-1.19.4-4.2.jar
placeholder-api-2.1.0+1.19.4.jar
polymer-bundled-0.4.11+1.19.4.jar
scarpet-graphics-0.1.5.jar 
server-hats-0.15.jar
servercore-1.3.5-1.19.4.jar
silk-all-1.9.8.jar
sleepwarp-2.0.0+1.19.4.jar
sodium-fabric-mc1.19.4-0.4.10+build.24.jar
spark-1.10.37-fabric.jar
starlight-1.1.1+fabric.ae22326.jar
toggleableitemframes-2.1.2-1.19.x.jar
viafabric-0.4.10+39-main.jar
voicechat-discord-fabric-2.1.0.jar
voicechat-fabric-1.19.4-2.4.11.jar
yet-another-config-lib-fabric-3.0.2+1.19.4.jar

Also, using the command `/season query` returns the length of time until the next season but uses the name of the currently season.

<img width="609" alt="image" src="https://github.com/lucaargolo/fabric-seasons/assets/135345834/3c1d8cea-3a6b-4283-8d6a-a4f32aa895e7">

**Comment by otomir23** [comment]
Same on 1.19.2

**Comment by ZelPie** [comment]
same thing happening with medieval minecraft 1.19.2

**Comment by xamy9000** [comment]
Same on Better MC 1.19.2.
A fix would be really appreciated!

**Comment by C8kilc8ac** [comment]
Same on BetterMC 1.19.2. Also it's snowing no matter what season it is. Beyond annoying.
