### ISSUE TITLE
setting time of day overwrites seasons

### ISSUE THREAD

**Issue by ZeburaBlack** [lucaargolo/fabric-seasons#14]
since typing /set time day, sets time to 0
it always resets seasons to day 1 of spring
same with all the other time of days.

**Comment by lucaargolo** [comment]
That's not an issue, it's intended behavior. Seasons are based in the world time, just like Stardew Valley and other similar games... As the days go by, the seasons change. If you keep resetting the world time to 0, you're just returning to the first day of your world.

**Comment by lucaargolo** [comment]
If you really want to use commands to change the time, you can try the `/time add` command, that way the time will actually pass, instead of being reset.
