### ISSUE TITLE
Ice not melting after winter ends

### ISSUE THREAD

**Issue by Mira721** [lucaargolo/fabric-seasons#146]
I play Better Minecraft, a mod which uses fabric seasons and in some biomes (Coconino meadow or maple taiga) the ice doesn't melt after the seasons change.

**Comment by GodsTitan** [comment]
This might have something to do with the immersive weathering mod, but I'm not sure. The ice not melting really does make the mod difficult to recommend in a modpack.

**Comment by plk01** [comment]
have same issue, with bunch of friends we start playing Better Minecraft fabric edition 1.19.2 and after winter season pass we notice the river around us frozen and isn't melting all season passd and nothing happened any solution?

**Comment by GodsTitan** [comment]
> have same issue, with bunch of friends we start playing Better Minecraft fabric edition 1.19.2 and after winter season pass we notice the river around us frozen and isn't melting all season passd and nothing happened any solution?

Maybe have a season's checker and replace all ice on sea level to water using a comand block, or just use worldedit and remove the mod until it's fixed

not sure if /gamerule mobgriefing false to see if it makes a difference

**Comment by Abduki** [comment]
will this fix be coming to 1.19.2? or only 1.20?
