### ISSUE TITLE
"minecraftDefaultFoliage" 

### ISSUE THREAD

**Issue by orionsleepie** [lucaargolo/fabric-seasons#149]
in "minecraftDefaultFoliage" there are options to configure foliage colours, but I cannot figure out what the codes are written in. if i put a hex code into it, will it work?

**Comment by lucaargolo** [comment]
You need to convert the hexadecimal value to an integer. You can use [this calculator](https://www.rapidtables.com/convert/number/hex-to-decimal.html) to do that.
![image](https://github.com/lucaargolo/fabric-seasons/assets/49497195/73a287b9-f2c4-40a4-9bae-89a399757c9e)
So for example, FF0000 (red) would be 16711680
