### ISSUE TITLE
Melted Ice causes spam waterfalls underground

### ISSUE THREAD

**Issue by spoorn** [lucaargolo/fabric-seasons#15]
When caves/tunnels underground generate scattered ice blocks, it seems this mod causes all those ice blocks to melt resulting in spam of waterfalls underground that causes massive FPS drops (gif is too large to embed):

https://i.imgur.com/fg81JXt.gifv

I found this happening on a modpack I'm working on.  I'm too lazy to figure out which mods are adding the underground ice, but you can reproduce this with this version of my modpack: https://www.curseforge.com/minecraft/modpacks/spoorns-world/files/3246578
Use world seed: "-6109615245211940038"
Go into spectator mode and look underground near the spawn point.  You can give yourself the nightvision effect to see better, but there are a ton of waterfalls in a 5 chunk radius around the spawn point.

A suggestion could be to prevent ice melting if it's underground.

**Comment by lucaargolo** [comment]
Yeah, all ice and snow blocks generated by the world will melt in hot biomes/seasons. I really haven't thought about cave mods tho. Preventing ice from melting if it's underground should solve this. I'll try to add that in the next update.

**Comment by jaz000** [comment]
I hit this too and the redwood biomes from Traverse (from the image/video) was one of those suffering from it. Took my fps from 200 down to zero! Not sure what you can do though apart from identify and remove everything spawning ice!
