### ISSUE TITLE
Trees are not affected by seasonal changes unlike crops

### ISSUE THREAD

**Issue by heyjudek** [lucaargolo/fabric-seasons#16]
As stated on the title, I think trees should be affected by the cropconfig settings just like crops and grow slower depending on the season.

**Comment by lucaargolo** [comment]
That's an awesome idea! I'll probably add that in a future update. Thanks for your suggestion!

**Comment by lucaargolo** [comment]
Starting on version 1.2, saplings are now also affected by the seasons.
