### ISSUE TITLE
[Feature request] Greenhouses and underground farms

### ISSUE THREAD

**Issue by seylerius** [lucaargolo/fabric-seasons#19]
It would be very cool if, when a crop was being grown aboveground and under glass, or under sufficient amounts of insulating dirt and stone, you could grow out-of-season crops at their normal speed. I think Serene Seasons does something similar. 

I think the ideal would be something along the lines of detecting that a crop is not directly exposed to the outside air, and has glass within maybe three to five blocks above it, for the greenhouse protection. Not sure what the best way to detect that your crop is sufficiently underground would be, though. That's harder to define clearly.

**Comment by lucaargolo** [comment]
Humm, that's a great idea! I'll probably just add a Greenhouse glass that you need to place above the crop if you want to build something on the surface. Checking if something is underground/sufficiently covered is easy, you just need to check if the crop is receiving any skylight.

**Comment by seylerius** [comment]
Oooh, good workaround for the underground detection. Leaves open the question of whether one ought to consider different materials sufficient insulation, but that's a nicely straightforward implementation. I like it.

**Comment by lucaargolo** [comment]
Starting on version 1.2, you can now craft Greenhouse Glass to build your farms without having to worry about the season! You can also build your farms underground if you prefer.
