### ISSUE TITLE
Tectonic support

### ISSUE THREAD

**Issue by SamuelUlep** [lucaargolo/fabric-seasons#197]
I can see that there is a terralith compat mod, but are there any plans for adding in a tectonic support or for both (terratonic)?

**Comment by mpustovoi** [comment]
Tectonic doesn't add new biomes. Therefore, what kind of compatibility is needed here?

**Comment by SamuelUlep** [comment]
My bad I think I had a brain fart writing this or there was an actual issue but I don't remember it anymore.
