### ISSUE TITLE
Snow and Ice generated from previous version will stay permanently if mod is updated during winter

### ISSUE THREAD

**Issue by tenguin** [lucaargolo/fabric-seasons#20]
There's a potential issue I think you might want to mention in the update notes.

With how the fix is implemented, I believe any region which has recently covered in ice or snow in the old version, will permanently retain all the previously generated vanilla snow and ice blocks if they update the mod while it is still Winter.

Might want to mention that in the notes for people updating; That they might want to stay on the old version and play their game locked to Spring for a while, until they've gotten rid of any stray snow/ice blocks, before updating.

Thanks for fixing that bug, I love this mod ;3

**Comment by lucaargolo** [comment]
![image](https://user-images.githubusercontent.com/49497195/117583190-241b6180-b0dc-11eb-8d8d-c373f8c982d8.png)
I think this should do. Thanks for remembering btw!

**Comment by tenguin** [comment]
rofl, that might be a little too over dramatic.
it also might be better worded like this, since the average player would probably get spooked by "break your world" when it's not that serious of a problem (and fixable by downgrading back to 1.1.x).

"WARNING: IF YOU'RE USING VERSION 1.1.X, MAKE SURE TO SET THE SEASON TO SPRING TO GET RID OF ALL THE PREVIOUS ICE AND SNOW IN YOUR WORLD BEFORE UPDATING.

BECAUSE OF A CHANGE IN IMPLEMENTATION, ALL THE ICE AND SNOW FROM WINTER IN THE OLD VERSION WILL NOT MELT IF YOU UPDATE TO THIS VERSION BEFORE GETTING RID OF IT."
