### ISSUE TITLE
[Bug] Crash when entering world on 1.3.1 [Fabric 1.20.1/0.16.5]

### ISSUE THREAD

**Issue by pokesmells** [lucaargolo/fabric-seasons#206]
https://mclo.gs/f8Ul5ah

**Comment by pokesmells** [comment]
Still has to do with Patchouli being installed

**Comment by lucaargolo** [comment]
You need to use Fabric Seasons 2.4 to use Fabric Seasons: Extras 1.3. I forgot to add it to the dependency requirement.
