### ISSUE TITLE
IMPORTANT BUG!

### ISSUE THREAD

**Issue by DeeChael** [lucaargolo/fabric-seasons#25]
If you install a mod that added custom dimensions, the custom dimensions won't be generated and you can't teleport to the custom dimensions by command "execute in modId:dimensionId run tp @s 0 100 0".
Plz fix it! It will cause a lot of players remove this mod!

I tried these mod that added custom dimensions:
[Agape Space Mod](https://www.curseforge.com/minecraft/mc-mods/moon-and-space-dimensions-fabric)
[The Aether Reborn](https://www.curseforge.com/minecraft/mc-mods/aether)

**Comment by RemagOfficial** [comment]
give a log

**Comment by DeeChael** [comment]
> give a log

It won't log anything but I tried it in game
You can try it:
Step 1: Install Fabric Season mod
Step 2: Install a mod that added custom dimensions like Agape Space Mod or The Aether Reborn
Step 3: Start the game
Step 4: Create a new world and play it
Step 5: Type "execute in " and it will show you what dimensions you can get to, it only show vanilla dimensions "overworld", "nether", "the_end"
Step 6: Remove Fabric Season mod and restart the game
Step 7: Create a new world and play it
Step 8: Type "execute in " again and it will show 3 vanilla dimensions and the modded dimensions
Step 6:

**Comment by lucaargolo** [comment]
![image](https://user-images.githubusercontent.com/49497195/118128590-7ce74480-b3d1-11eb-8aa1-cc2f727f27a4.png)
Just tested this in the latest release and it's working fine. Are you sure another mod isn't breaking your world?

**Comment by lucaargolo** [comment]
Since no one said anything, and I tested this and everything worked fine, I'll be closing this issue.
