### ISSUE TITLE
Winter Snows Only Appears on New Chunks

### ISSUE THREAD

**Issue by Blunder-G** [lucaargolo/fabric-seasons#27]
Look at the map on top right corner, chunk borders are extremely clear. PS: I'm in Creative mode in taht photos.

![2021-05-16_15 08 51](https://user-images.githubusercontent.com/56030297/118403777-ab3a7d80-b678-11eb-8bdb-4ff73b7ec903.png)
![2021-05-16_15 01 27](https://user-images.githubusercontent.com/56030297/118403782-b1c8f500-b678-11eb-91ee-544bb32deaa2.png)

**Comment by lucaargolo** [comment]
That's not a bug, that's just how it works... When you generate new chunks and your world is in the winter, those chunks will generate with snow, but your old chunks will need actual snow/rain, to get snow precipitation. Unfortunately, the chunk borders will be harsh and ugly, but there's nothing I can do about it.
