### ISSUE TITLE
A Custom Config For Moded Biomes: "blacklistedBiomes"  and "affectableSeasonsList"

### ISSUE THREAD

**Issue by Blunder-G** [lucaargolo/fabric-seasons#29]
There should be a blacklist in the config file. In this way, we can deactivate foliage and grass color that are affected by the seasons. 

Ex:

"blaclistedBiomes": traverse:autumnal_forest traverse:autumnal_forest_hills

And:

  "foliageColorList": [],
  "grassColorList": [],
  **"affectableSeasonsList": [**
        { x biome
          "fallAffectsFoliegeColor": true/false
          "fallAffectsGrassColor": true/false
          "fallAffectsCrops": true/false

           other seasons bla bla...
],

**Comment by lucaargolo** [comment]
You can already disable color change in custom biomes by creating a custom foliage and grass color entry in the config file using the original biome values. Locking some biomes on specific seasons would probably be very confusing and hard to add. That's not on my plans right now, sorry.
