### ISSUE TITLE
Crops won't drop?

### ISSUE THREAD

**Issue by hanzotitmada** [lucaargolo/fabric-seasons#3]
I just recently downloaded Seasons and it's been working great. However, for some reason, my crops... don't drop? When I break a potato, for example, the plant breaks and it's bare farmland, but no drops. All other mob drops are working fine, as are other block drops. I am playing on Creative/Peaceful.

**Comment by lucaargolo** [comment]
I'm not understanding your problem... Aren't blocks not supposed to drop anything in creative? Anyway, if you could record a video before using the mod and after it would be very helpful!

**Comment by hanzotitmada** [comment]
So, it took me some doing to get all my mods (as in, JUST OPTIFINE+FABRIC) to actually work and I'm honestly not sure... how? So I'm a bit nervous to try and turn them off. However, as you can see, the villagers are harvesting+planting no problem. Also, if I kill a sheep, it drops wool+meat, zombies drop flesh after burning during the day, if I break down a tree trunk the leaves drop saplings/sticks/etc... It's only the crops! They work normally in survival mode, but I usually play on creative and the crops still drop on vanilla creative. 
![image](https://user-images.githubusercontent.com/74527545/99304324-351ba200-2820-11eb-85b3-c1f30356998f.png) 
![image](https://user-images.githubusercontent.com/74527545/99304427-59777e80-2820-11eb-96fd-b699d952bfb6.png)

**Comment by lucaargolo** [comment]
So, I'm still not understanding your problem. I just tested it and crops definitely do not drop anything if broken while on creative mode. Also, this mod is currently not messing with block's drops, so the issue is probably not on my end.

**Comment by hanzotitmada** [comment]
I have been playing on 1.14 for a while before opening this world up, so maybe it's something that minecraft changed over the updates? It was just kinda confusing to me.
