### ISSUE TITLE
Calendar Tooltip Popup

### ISSUE THREAD

**Issue by Guardian259** [lucaargolo/fabric-seasons#34]
Allow for the Calendar to display its tooltip in a popup when moused over in a Item frame. This adds both style and convenience to the calendar and falls in line with how actual players interact with said item.

**Comment by Guardian259** [comment]
I may end up making a PR for this ~~depending on my workload~~

**Comment by lucaargolo** [comment]
As of version 2.0, all items and blocks have been moved to [Fabric Seasons: Extras](https://github.com/lucaargolo/fabric-seasons-extras). The calendar item has been remade, and you can now place it on a wall and it'll show up a tooltip popup if you sneak.
