### ISSUE TITLE
Stratify Crop Growth

### ISSUE THREAD

**Issue by Guardian259** [lucaargolo/fabric-seasons#35]
Stratify put Crop growth penalties by Crop types. This would incentives players to try different food sources, keeping various food types on hand durring different seasons.

Crop categories could be comprised as such:

Spring Crops
Temperate Crops (possibly current settings?)
Winter Crops

Crops that come to mind are primarily carrots. I could see the stratification of crop growth penalties being an interesting and definitive gameplay loop in and of itself

**Comment by ChristopherTheBoss** [comment]
This is an interesting idea but players should always be able to make a greenhouse or make an artificial microclimate to grow crops outside of their season.
