### ISSUE TITLE
Snow does not disappear 

### ISSUE THREAD

**Issue by imcasper** [lucaargolo/fabric-seasons#43]
I play in version:
seasons-1.16.5-1.2-BETA.jar

In the first winter in the game, I thought that the seasons are very long, and I reduced the length of the season in the config (on the server and on the client).

Summer has come, but a small part of the snow (cubes) remains.

After a full cycle of seasons, these cubes remain.

Snow cubes can be removed manually.

**Comment by lucaargolo** [comment]
Hi, this mod does not make snow accumulate in layers. You're probably using another mod that does that, and when snow blocks get formed they don't melt (as they weren't supposed to form in the winter)

**Comment by NotJustAnna** [comment]
It's not a bug, it's a feature.

Gotta live that true canadian experience.
![image](https://user-images.githubusercontent.com/6955035/132966298-4e9d91b5-94f7-4db7-b6f4-651600214f58.png)

**Comment by FisbanRegner** [comment]
i actually have the same issue running 1.17.1 with the 1.18 additions this isn't a mod incompatibility the snow accumulation is a new feature added to minecraft as the snow falls the layers build up usually ending before blocks are formed but the snow lasts so long in the winter time that after a few winters the entire world is covered with snow blocks that don't melt

**Comment by imcasper** [comment]
First of all, I really like this idea and this mod. This improves the gaming experience fantastically!

So...
As a user, I want the snow to melt in the spring. I don't care where the snow block came from. I can put a block of snow and ice myself, and I hope that it will melt in the summer. This is a normal experience for a season change mod. The player will have to give up the geothermal generator.

I don't know how the melting of snow is implemented now. I think it's important to consider the creation of "frozen blocks"
-any mods
-mechanics of the game
-in any season
Blocks may also already exist at the time the mod is turned on.

**Comment by imcasper** [comment]
**I checked. I think that it is blocks from you mod, because it name is "seasons:seasonal_snow"**

I clean it for himself with world-edit-mod:
/replacenear 200 seasons:seasonal_snow air

**Comment by imsoenthused** [comment]
I am experiencing the same thing. Building anywhere that it snows is awful because it just gets covered in snow blocks. I wonder if the temperature change setting makes any difference? The mod makes it snow more often, which makes snow accumulating into blocks go from rare to guaranteed, and snow blocks don't melt, so any non-hot biome just turns into a faux arctic biome after a winter or two. I'd just like to see the snow blocks turn back into partial blocks over time outside of winter. They should only be permanent in arctic biomes. Right now, if I want to use Seasons, I have to run around every spring using console commands to clear snow, and I love the ambiance but I'm not sure it's worth the annoyance.

**Comment by AmonRay** [comment]
same issue for me, full block of snow does not disappear

**Comment by kotisorion** [comment]
> 
> 
> i actually have the same issue running 1.17.1 with the 1.18 additions this isn't a mod incompatibility the snow accumulation is a new feature added to minecraft as the snow falls the layers build up usually ending before blocks are formed but the snow lasts so long in the winter time that after a few winters the entire world is covered with snow blocks that don't melt


This is exactly what's happening to me. The snow makes the game very annoying after first winter, and unplayable after the second.

**Comment by Aimela** [comment]
If it is caused by another mod, maybe add an option to allow full seasonal_snow blocks to melt for compatibility's sake.

**Comment by imsoenthused** [comment]
A note for anyone else experiencing this issue, editing the config for seasons and seeing temperature change to false "fixes" it. You don't get some of the best parts of the mod in winter, but at least it won't turn temperate biomes in to Arctic ones.

**Comment by wolfkidsounds** [comment]
It would be cool if you could evaluate this again.

A config option to enable/disable this behavior would be great.

---

I guess when snow accumulates you get a different block that is staying there and not gets cleaned up.

**Comment by itsdinkd** [comment]
happens in 1.18

@lucaargolo can you look into this please? pretty sure this isn't the intention of the mod. Every single biome is filled with snow starting on a new world. changing time does nada.

**Comment by farsenfsd** [comment]
It would be great if you could add an option ot the mod to make full snow blocks melt, it would allow for compatibility with snow accumulation mods

**Comment by lucaargolo** [comment]
As of version 2.0, the snow melting behavior changed and I'm pretty sure this shouldn't happen anymore.

**Comment by itsdinkd** [comment]
Insert 2 years later meme here 🤣
