### ISSUE TITLE
Days change at the wrong speed with Time & Wind

### ISSUE THREAD

**Issue by ImpSpy2** [lucaargolo/fabric-seasons#46]
Fabric Seasons expects the day length to be 24000 ticks so when you change the day length using the Time & Wind mod the days will move at the wrong speed. Maybe an option to set the length of the day in the config to match what is set in Time & Wind would be useful?

**Comment by lucaargolo** [comment]
This mod literally does not care about the day length. Yes, the season is supposed to last 28 normal days (28*24000) but this value is already configurable...
