### ISSUE TITLE
I try to translate into Chinese

### ISSUE THREAD

**Issue by GodSayFK** [lucaargolo/fabric-seasons#5]
Can put it in the mod
My English is not will.
Please forgive me if there are some errors

{
  "block.seasons.season_detector": "季節探測器",
  "item.seasons.season_calendar": "季節日曆",
  "tooltip.seasons.spring": "§a春天",
  "tooltip.seasons.summer": "§6夏季",
  "tooltip.seasons.fall": "§4秋天",
  "tooltip.seasons.winter": "§b冬天",
  "tooltip.seasons.calendar_info_1": "§9目前在: ",
  "tooltip.seasons.calendar_info_2": " §7還剩幾天 ",
  "tooltip.seasons.faster_grow": "§a這個季節的農作物生長會更快",
  "tooltip.seasons.normal_grow": "§9這個季節的農作物生長會正常生長",
  "tooltip.seasons.slowed_grow": "§6這個季節的農作物生長需要更長的時間",
  "tooltip.seasons.not_grow": "§c這個季節收成不好",
  "tooltip.seasons.show_more": "§7按 §9{KEY} §7顯示更多:",
  "tooltip.seasons.crop_multipliers": "§7這種作物會受到怎樣的影響:",

  "text.autoconfig.seasons.title": "季節配置",

  "text.autoconfig.seasons.category.seasonBehaviour": "季節行為",
  "text.autoconfig.seasons.option.seasonLength": "換季時間（ticks）",
  "text.autoconfig.seasons.option.seasonLock": "季節鎖定",
  "text.autoconfig.seasons.option.seasonLock.isSeasonLocked": "季節鎖定",
  "text.autoconfig.seasons.option.seasonLock.lockedSeason": "鎖定季節",
  "text.autoconfig.seasons.option.doTemperatureChanges": "啟用溫度變化",

  "text.autoconfig.seasons.category.itemsAndBlocks": "物品和方塊",
  "text.autoconfig.seasons.option.isSeasonCalendarEnabled": "啟用季節日曆",
  "text.autoconfig.seasons.option.isSeasonDetectorEnabled": "啟用季節檢測器",

  "text.autoconfig.seasons.option.seasonLock.isSeasonLocked.@Tooltip": "如果啟用，您的世界將停留在配置的季節中",

  "text.autoconfig.seasons.option.seasonLength.@Tooltip[0]": "配置每個季節持續多長時間",
  "text.autoconfig.seasons.option.seasonLength.@Tooltip[1]": "24000 ticks = 1 天(Minecraft 時間)",
  "text.autoconfig.seasons.option.seasonLength.@Tooltip[2]": "672000 ticks = 28 天(Minecraft 時間)",

  "text.autoconfig.seasons.option.doTemperatureChanges.@Tooltip[0]": "如果啟用，溫帶生物群落將在冬季形成冰雪 ",
  "text.autoconfig.seasons.option.doTemperatureChanges.@Tooltip[1]": "寒冷生物群落將在夏季融化並下雨.",

  "text.autoconfig.seasons.category.hardcodedColors": "Hardcoded Colors",

  "text.autoconfig.seasons.option.minecraftDefaultFoliage": "樹葉",
  "text.autoconfig.seasons.option.minecraftDefaultFoliage.springColor": "春天",
  "text.autoconfig.seasons.option.minecraftDefaultFoliage.summerColor": "夏天",
  "text.autoconfig.seasons.option.minecraftDefaultFoliage.fallColor": "秋天",
  "text.autoconfig.seasons.option.minecraftDefaultFoliage.winterColor": "冬天",

  "text.autoconfig.seasons.option.minecraftSpruceFoliage": "雲杉樹葉",
  "text.autoconfig.seasons.option.minecraftSpruceFoliage.springColor": "春天",
  "text.autoconfig.seasons.option.minecraftSpruceFoliage.summerColor": "夏天",
  "text.autoconfig.seasons.option.minecraftSpruceFoliage.fallColor": "秋天",
  "text.autoconfig.seasons.option.minecraftSpruceFoliage.winterColor": "冬天",

  "text.autoconfig.seasons.option.minecraftBirchFoliage": "樺樹葉",
  "text.autoconfig.seasons.option.minecraftBirchFoliage.springColor": "春天",
  "text.autoconfig.seasons.option.minecraftBirchFoliage.summerColor": "夏天",
  "text.autoconfig.seasons.option.minecraftBirchFoliage.fallColor": "秋天",
  "text.autoconfig.seasons.option.minecraftBirchFoliage.winterColor": "冬天",

  "text.autoconfig.seasons.option.minecraftSwampGrass1": "沼澤草1",
  "text.autoconfig.seasons.option.minecraftSwampGrass1.springColor": "春天",
  "text.autoconfig.seasons.option.minecraftSwampGrass1.summerColor": "夏天",
  "text.autoconfig.seasons.option.minecraftSwampGrass1.fallColor": "秋天",
  "text.autoconfig.seasons.option.minecraftSwampGrass1.winterColor": "冬天",

  "text.autoconfig.seasons.option.minecraftSwampGrass2": "沼澤草2",
  "text.autoconfig.seasons.option.minecraftSwampGrass2.springColor": "春天",
  "text.autoconfig.seasons.option.minecraftSwampGrass2.summerColor": "夏天",
  "text.autoconfig.seasons.option.minecraftSwampGrass2.fallColor": "秋天",
  "text.autoconfig.seasons.option.minecraftSwampGrass2.winterColor": "冬天",

  "text.autoconfig.seasons.option.isDefaultHSBShiftEnabled": "啟用默認HSB色彩模式t",
  "text.autoconfig.seasons.option.isDefaultHSBShiftEnabled.@Tooltip[0]": "如果啟用，則沒有自定義配置的樹葉顏色變化",
  "text.autoconfig.seasons.option.isDefaultHSBShiftEnabled.@Tooltip[1]": "將根據配置的默認的顏色.",
  "text.autoconfig.seasons.option.defaultHSBShift": "默認 HSB shift",
  "text.autoconfig.seasons.option.defaultHSBShift.springHSBShift": "春天 HSB色彩模式",
  "text.autoconfig.seasons.option.defaultHSBShift.springHSBShift.hue": "色調",
  "text.autoconfig.seasons.option.defaultHSBShift.springHSBShift.saturation": "飽和",
  "text.autoconfig.seasons.option.defaultHSBShift.springHSBShift.brightness": "亮度",
  "text.autoconfig.seasons.option.defaultHSBShift.summerHSBShift": "春天 HSB色彩模式",
  "text.autoconfig.seasons.option.defaultHSBShift.summerHSBShift.hue": "色調",
  "text.autoconfig.seasons.option.defaultHSBShift.summerHSBShift.saturation": "飽和",
  "text.autoconfig.seasons.option.defaultHSBShift.summerHSBShift.brightness": "亮度",
  "text.autoconfig.seasons.option.defaultHSBShift.fallHSBShift": "秋天 HSB色彩模式",
  "text.autoconfig.seasons.option.defaultHSBShift.fallHSBShift.hue": "色調",
  "text.autoconfig.seasons.option.defaultHSBShift.fallHSBShift.saturation": "飽和n",
  "text.autoconfig.seasons.option.defaultHSBShift.fallHSBShift.brightness": "亮度",
  "text.autoconfig.seasons.option.defaultHSBShift.winterHSBShift": "冬天 HSB色彩模式",
  "text.autoconfig.seasons.option.defaultHSBShift.winterHSBShift.hue": "色調",
  "text.autoconfig.seasons.option.defaultHSBShift.winterHSBShift.saturation": "飽和",
  "text.autoconfig.seasons.option.defaultHSBShift.winterHSBShift.brightness": "亮度",
  "text.autoconfig.seasons.option.foliageColorList": "自定義樹葉顏色",
  "text.autoconfig.seasons.option.grassColorList": "自定義草的顏色",
  "text.autoconfig.seasons.option.BiomeColors": "生物群落顏色",
  "text.autoconfig.seasons.option.BiomeColors.biomeIdentifier": "生物群落識別符",
  "text.autoconfig.seasons.option.BiomeColors.colors.springColor": "春天",
  "text.autoconfig.seasons.option.BiomeColors.colors.summerColor": "夏季",
  "text.autoconfig.seasons.option.BiomeColors.colors.fallColor": "秋天",
  "text.autoconfig.seasons.option.BiomeColors.colors.winterColor": "冬天",

  "text.autoconfig.seasons.category.crops": "農作物",
  "text.autoconfig.seasons.option.isSeasonMessingCrops": "啟用季節作物",
  "text.autoconfig.seasons.option.isSeasonMessingBonemeal": "啟用季節骨粉",
  "text.autoconfig.seasons.option.defaultCropConfig": "默認農作物配置",
  "text.autoconfig.seasons.option.defaultCropConfig.@Tooltip": "Crops that do not have custom configs will follow these modifiers",
  "text.autoconfig.seasons.option.defaultCropConfig.springModifier": "春天 modifier",
  "text.autoconfig.seasons.option.defaultCropConfig.summerModifier": "夏天 modifier",
  "text.autoconfig.seasons.option.defaultCropConfig.fallModifier": "秋天 config",
  "text.autoconfig.seasons.option.defaultCropConfig.winterModifier": "冬天 modifier",
  "text.autoconfig.seasons.option.cropConfigs": "自定義農作物配置",
  "text.autoconfig.seasons.option.CropConfig": "農作物配置",
  "text.autoconfig.seasons.option.CropConfig.cropIdentifier": "農作物標識符",
  "text.autoconfig.seasons.option.CropConfig.springModifier": "春天 modifier",
  "text.autoconfig.seasons.option.CropConfig.summerModifier": "夏天 modifier",
  "text.autoconfig.seasons.option.CropConfig.fallModifier": "秋天 modifier",
  "text.autoconfig.seasons.option.CropConfig.winterModifier": "冬天 modifier",

  "text.autoconfig.seasons.category.animals": "動物",
  "text.autoconfig.seasons.option.doAnimalsBreedsInWinter": "啟用冬季繁殖"

}

**Comment by Neubulae** [comment]
下次建议使用pull request
顺便参考一下繁中地区Minecraft所使用的语言规范哦
