### ISSUE TITLE
Compatiability with the Fabric mod Croptopia

### ISSUE THREAD

**Issue by uwni** [lucaargolo/fabric-seasons#50]
Hi, I found that some fruits in fruit trees(like peach, orange) in the mod [Croptopia](https://www.curseforge.com/minecraft/mc-mods/croptopia-fabric) still get growing even in winter. 
Idk if it Is a bug or a feature

**Comment by lucaargolo** [comment]
As of version 2.0, there's a Croptopia compatibility pack. You can find it here: https://github.com/lucaargolo/fabric-seasons-croptopia-compat
