### ISSUE TITLE
Bug Grass not updating with sheep

### ISSUE THREAD

**Issue by lordzues40** [lucaargolo/fabric-seasons#51]
Let me start off with, Im Not totaly sure if its this mod or not that is causeing the problem but when sheep eat the grass. the grass block does not turn to dirt.
and this brakes wool farms.
just thought sense this mod changes the color of the grass blocks (and other blocks) that may be something got changed that prevents the sheep from changing the block to dirt after eating the grass.

**Comment by lucaargolo** [comment]
Heyy, this probably wasn't being caused by this mod, since it doesn't change anything related to grass/dirt.
