### ISSUE TITLE
Config toggle for snow cover/freezing in winter

### ISSUE THREAD

**Issue by Zentheon** [lucaargolo/fabric-seasons#56]
The concept of seasons is a really cool one, but winter itself is particularly invasive part of it. Having a balanced snow/ice accumulation mechanic seems like it'd be tricky given game limitations, but either way having everything frozen over for new chunk generation and then switching to a new season is pretty jarring. It'd be nice to have a few toggles for generating snow or ice in new chunks as well as passive water freezing in the winter.

**Comment by lucaargolo** [comment]
You can already disable the temperature changes in the config file. Changing how ice/snow happens in the game is out of the scope of this mod. All this mod does is change the biome's temperature and precipitation, enabling snow/ice to form during the winter and melt during warmer seasons.
