### ISSUE TITLE
Documentation on "cropConfigs"?

### ISSUE THREAD

**Issue by mosharky** [lucaargolo/fabric-seasons#58]
I suppose a general config documentation would be quite nice

**Comment by LonelyMusicDisc** [comment]
Bumping this (if that's even a thing on github), I really want to add my own support for farmer's delight!

**Comment by lucaargolo** [comment]
Hey, I'm yet to do documentation on all the configs for this mod, but here's an example config for custom crop modifiers. 
![image](https://user-images.githubusercontent.com/49497195/181307560-e87ad3e7-bf87-475a-bf7f-46f982c11f86.png)

**Comment by lucaargolo** [comment]
As of version 2.0, the crop config system is now handled by datapacks. You can check [this](https://github.com/lucaargolo/fabric-seasons/tree/1.19/src/main/resources/data/minecraft/seasons/crop) for a how-to example.
