### ISSUE TITLE
Could you make it changethe sky colors as well?

### ISSUE THREAD

**Issue by DuendeInexistente** [lucaargolo/fabric-seasons#67]
Like [this](https://youtu.be/N_n2_2xXzy4?t=367)
![image](https://user-images.githubusercontent.com/20157727/160722760-522df1ce-4862-44d3-9fc1-7b75ed1be1d4.png)

**Comment by lucaargolo** [comment]
Heyy, unfortunately, this is currently out of the scope of this mod right now. But thanks for the suggestion,
