### ISSUE TITLE
New calendar icon

### ISSUE THREAD

**Issue by Disketaa** [lucaargolo/fabric-seasons#68]
This item icon drawn by me feel free to use

![image](https://user-images.githubusercontent.com/76956762/166660192-059f5505-fae4-4493-9167-ffed506df4ea.png)
![image](https://user-images.githubusercontent.com/76956762/166660214-627cbd3d-ff39-401a-a3fe-a0a882cb2c3e.png)
![image](https://user-images.githubusercontent.com/76956762/166660230-3cdf0d34-cb2f-4757-add8-a5ff522a4337.png)

Icon:
![season_calendar](https://user-images.githubusercontent.com/76956762/166660259-20955e9a-c03e-4e9d-a03b-546233436685.png)

**Comment by lucaargolo** [comment]
As of version 2.0, all items and blocks have been moved to [Fabric Seasons: Extras](https://github.com/lucaargolo/fabric-seasons-extras). The calendar item has been remade and it now has a dynamic texture. 

I'm very sorry for not answering you, was very busy last year and I'm only now getting back to maintaining this mod. Thank you very much for the texture, but as the new calendar is dynamic, this can't be used anymore.
