### ISSUE TITLE
Reduce the rate at which snow melts

### ISSUE THREAD

**Issue by Sunconure11** [lucaargolo/fabric-seasons#69]
I had noticed, that in the past, with this mod installed, as soon as the seasons shifted, snow would melt very fast, causing massive lag. Would it be possible to have it melt in a more gradual fashion?

**Comment by SpookLad** [comment]
It also still melts quickly in Winter, which is extremely odd.

**Comment by Sunconure11** [comment]
@lucaargolo

**Comment by lucaargolo** [comment]
Hey, sorry for not answering this. Snow melting speed is handled by vanilla, this mod doesn't change anything about it. If it was melting abnormally fast, it was probably being caused by another mod, or by a high randomTickUpdates value.
