### ISSUE TITLE
Calendar's in Item Frames

### ISSUE THREAD

**Issue by RoY7x** [lucaargolo/fabric-seasons#70]
Would be rather useful in my opinion to have the ability to see the date/time til the season ends when the calendar is placed in an item frame, similar to how maps and clocks can be nice to have placed on a wall for decoration. Having a wall calendar would be a nice addition I would think, especially since it only displays the remaining days currently in the tooltip. Perhaps have some sort of visual way then to show remaining days, than just using the tooltip information?

**Comment by hakanai** [comment]
Yes, the expected thing for a calendar would be to put it on a wall.

I don't think it should even need an item frame but with real calendars, it sits on a hook.

**Comment by lucaargolo** [comment]
As of version 2.0, all items and blocks have been moved to [Fabric Seasons: Extras](https://github.com/lucaargolo/fabric-seasons-extras). The calendar item has been remade, and you can now place it on a wall.
