### ISSUE TITLE
Make this mod server-side.

### ISSUE THREAD

**Issue by DiePutin3782** [lucaargolo/fabric-seasons#71]
I think that this mod should be server-side, why isn't it server- side? because you basically replaced all snow in vanilla Minecraft with the modded version, I don't really see the point in that when you can just use the vanilla ice and snow and make it pile up and melt.

**Comment by realguyman** [comment]
> why isn't it server- side?

@Theobot3782 Because a lot of Fabric Seasons' features require both the server and client to have the mod installed.

**Comment by lucaargolo** [comment]
As of version 2.0, you can use the mod as a server-side mod, or as a client-side mod. Although it's still recommended that you install the mod on both sides to get the full experience.
