### ISSUE TITLE
[Feature request] Croparia Greenhouse compatibility?

### ISSUE THREAD

**Issue by MSandro** [lucaargolo/fabric-seasons#73]
The Mod Croparia has a Greenhouse Block. Would it be possible to allow crops to grow in it even if its winter?

**Comment by lucaargolo** [comment]
As of version 2.0, the Greenhouse system has been rewritten and improved. Also, all items have been moved to [Fabric Seasons: Extras](https://github.com/lucaargolo/fabric-seasons-extras). Greenhouse glasses need to implement custom tickable code for them to work, so this can only be implemented on Croparia's side.
