### ISSUE TITLE
[1.18.2] crash after setting time fast

### ISSUE THREAD

**Issue by TobiPeterG** [lucaargolo/fabric-seasons#78]
Hey there,

I experimented a bit with mods in fabric and noticed that the game reliably crashes when I add large amounts of time (/time add 2222222 multiple times).

The crash log: https://pastebin.com/wSBgj1nx

Should any additional information be required, I'd be very happy to help!

**Comment by lucaargolo** [comment]
This crash was fixed by version 2.0 of the mod.
