### ISSUE TITLE
Seasons colors are mismatched?

### ISSUE THREAD

**Issue by RDKRACZ** [lucaargolo/fabric-seasons#8]
1st photo - fall, 2nd - winter. The grass looks more alive in winter than in fall but seems like leaves are set properly. So shouldn't the grass color palette in winter be replaced by the fall palette and vice-versa?
![2021-01-27_15 41 47](https://user-images.githubusercontent.com/43277609/106008120-49e5a300-60b7-11eb-85fd-b753517621ea.png)
![2021-01-27_15 41 33](https://user-images.githubusercontent.com/43277609/106008190-579b2880-60b7-11eb-827c-26188cbfa5fa.png)

**Comment by lucaargolo** [comment]
Huh weird, I might have mismatched something... If you take a look at the oak leaves you can see the one in the second picture matches the grass color in the first picture. I'll take a look at it.

**Comment by lucaargolo** [comment]
What biome is this?

**Comment by RDKRACZ** [comment]
Snowy taiga I think.

**Comment by lucaargolo** [comment]
Hmmm, the biome your camera was pointed at was actually a snowy tundra. (Spruce tree doesn't spawn on regular plains). I took a look at the colormaps and they are in fact correct. What happened is that I wasn't able to fine-tune the color map in a way that allows all the biomes to look good in all seasons. If it really bothers you, you can always make your own custom colormaps using a resource pack. You can also configure exact colors for a specific biome in the mod's config.

**Comment by realguyman** [comment]
@lucaargolo Serene Seasons was extremely good at determining custom color maps. You could take a loot at their source code and see how they did it: https://github.com/Glitchfiend/SereneSeasons/tree/SS-1.16.x-4.x.x

**Comment by lucaargolo** [comment]
Heyy. As of version 2.0 all colormaps have been remade.
