### ISSUE TITLE
Can I disable only the winter season?

### ISSUE THREAD

**Issue by oDisMal** [lucaargolo/fabric-seasons#80]
I'm looking to disable the winter season or even set its duration very short.
Thanks,

**Comment by Guimoute** [comment]
I support that suggestion because I would like to keep only spring and winter as seasons!

**Comment by lucaargolo** [comment]
Heyy, you currently can't do that, and it's also out of the scope of the mod. If you want winter to be less harsh, you can disable the temperature changes in the config file, that will stop snow/ice from forming on warmer biomes, but it'll keep the custom colors.
