### ISSUE TITLE
Support for croptopia? (fruit leaves/seeds)

### ISSUE THREAD

**Issue by Mnky313** [lucaargolo/fabric-seasons#81]
I followed the other issue to try and manually add this but adding the leaf block (in the screenshot it's 'plum_crop') doesn't appear to work, the leaves still grow fruit in seasons that they should not be able to grow.

![image](https://user-images.githubusercontent.com/23646586/183462910-3989b18f-630c-4368-b8b7-a78e23df6231.png)

![image](https://user-images.githubusercontent.com/23646586/183463224-39a8cc98-c668-42b2-b288-15ff55ab2c2a.png)

The saplings were natively supported and do function as intended.

As for seeds, the crops themselves work as expected (grow based on seasons) however the seed items don't show the tooltip for different growth speeds.

![image](https://user-images.githubusercontent.com/23646586/183464178-1457e211-54c0-41a7-a593-26f96355642d.png)

![image](https://user-images.githubusercontent.com/23646586/183464455-3cf34142-f513-40f3-a4df-dbae85902051.png)

![image](https://user-images.githubusercontent.com/23646586/183464343-19008ba3-73cc-40c9-8b5d-927168573ebd.png)

**Comment by lucaargolo** [comment]
As of version 2.0, there's a Croptopia compatibility pack. You can find it here: https://github.com/lucaargolo/fabric-seasons-croptopia-compat
