### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by jarocajavi** [lucaargolo/fabric-seasons#84]
Hello, i open a ticket in Supplementaries page, but i think must be here.
https://www.curseforge.com/minecraft/mc-mods/supplementaries/issues/449

My second crash was be with "mangle_seed" and is the reason i am here, see the pattern, 2 different seeds and same crash.
https://bytebin.lucko.me/37eKMVae7B

Thanks anyway i hope this can be helpfull

**Comment by XOX-CH** [comment]
I'm getting the error Crash: Player Entity. I crashed when changing the time with the command: /time set 19500000d. My saves are therefore inaccessible Delete MOD Crash: Player Entity -

**Comment by jarocajavi** [comment]
Sorry, what?

**Comment by lucaargolo** [comment]
Closing this since I was never able to properly reproduce it and the mod code changed a lot since it was reported.
