### ISSUE TITLE
Blocks rendered differently when joining a server without Fabric Seasons

### ISSUE THREAD

**Issue by ux92** [lucaargolo/fabric-seasons#85]
Hello,

I have found that whenever I join a server without Fabric Seasons (even vanilla unmodded) while using a Fabric client with Fabric Seasons installed, some blocks are rendered as different blocks, for example Terracotta is rendered as Observers, Cactus is rendered as Snow layers, some two-tall flowers are rendered as Ice Blocks, Kelp is rendered as Bamboo, and possibly others that I'm not aware of. They even behave like said blocks in my client, or partially, which leads to incongruences on how the server processes things I do (I can somehow stand on top of Kelp because I see them as Bamboo Stalks, but if I break it, I clip through).

This also leads to massive lag spikes when looking at a direction with many blocks affected.

I have tried removing all other mods except Sodium, Iris and Starlight; I don't think either of those could be the problem?

It works fine when joining a server that has Fabric Seasons, but having to remove the jar file and put it back again depending on which server I want to join is annoying.

Has anyone ran into this issue and know a fix?

Thanks.

**Comment by lucaargolo** [comment]
This was happening cause older versions of the mod needed to be installed on both the client and the server. As of version 2.0, you can use the mod as a server-side mod, or as a client-side mod. Although it's still recommended that you install the mod on both sides to get the full experience.
