### ISSUE TITLE
[SUGGESTION] Remove/Add snow on loading prev. chunk

### ISSUE THREAD

**Issue by Shazuli** [lucaargolo/fabric-seasons#86]
***Hi***

It would be nice if snow got removed/added when a previously generated chunk is loaded again if it had snow in it or not other than just generating snow for a new chunk in the winter. Definetely would reduce the number of block updates when passing from winter to spring.
[Serene Tweaks](https://www.curseforge.com/minecraft/mc-mods/serene-tweaks) does that.

**Comment by mnfu** [comment]
Either this or just have an option to disable winter snowfall / freezing because of the block update lag. Brings modded servers tps down when no other mod is causing such a performance hit.

Edit: I do like this mod, but this is the one drawback making me consider removing it unfortunately

**Comment by lucaargolo** [comment]
> Either this or just have an option to disable winter snowfall / freezing because of the block update lag. Brings modded servers tps down when no other mod is causing such a performance hit.
> 
> Edit: I do like this mod, but this is the one drawback making me consider removing it unfortunately

You can already disable temperature changes in the config file, so winter will not make snow/ice happen in warmer biomes, and you'll still keep the color changes.

**Comment by lucaargolo** [comment]
Although this requested feature is very cool, it seems to be hard to implement, and currently, it's out of scope for this mod. I might take a look at it again in the future.

**Comment by lucaargolo** [comment]
Closing this since it's the same as #9
