### ISSUE TITLE
Winter breaks sugarcanes. Frosted ice could prevent that.  

### ISSUE THREAD

**Issue by Guimoute** [lucaargolo/fabric-seasons#88]
Hello,

I love the winter part of this mod. Everything looks so nice. The only problem I've seen is that sugarcanes on the shores end up breaking when everything freezes. My suggestion would be to turn water blocks into either `seasons:ice` or `seasons:frosted_ice` depending on whether sugarcanes are watered by this block, which is defined by finding at least one sugarcane in the cross above the water source.

Using frosted ice is neat because you inherit the vanilla behavior of not breaking crops and you only have ice-related code on your side. An alternative solution would be to change the crops themselves to support `seasons:ice` just like they support `minecraft:frosted_ice`, but then you get sugarcane code in your mod which might not be ideal. That alternative does not require the neighbouring blocks checks though.

**Comment by lucaargolo** [comment]
Heyy, I think you can just put a torch next to the water source and that will prevent ice from forming. In any case, this mod doesn't change ice/snow vanilla behavior, so it's out of the scope of the mod to change something like that. All this mod does is change the biome's temperature and precipitation, enabling snow/ice to form during the winter and melt during warmer seasons.
