### ISSUE TITLE
Suggestion: Make Calendars more interactive

### ISSUE THREAD

**Issue by FumpleWumper** [lucaargolo/fabric-seasons#90]
I am using the mod in a server with some friends and it's very bothersome having to pass around the same calendar on an item frame to check how many days we have left until next season, it would be cool if we could check the calendar without having to hover over it in our inventory, perhaps by it having different colors so we can see it when it's hanged on an item frame? Or even by giving it a 3D model that we can hang on the wall without the need of an item frame, or really anything that makes it easier to check the calendar outside of our inventory
Thank you and keep up the good work! I love this mod so far

**Comment by lucaargolo** [comment]
As of version 2.0, all items and blocks have been moved to [Fabric Seasons: Extras](https://github.com/lucaargolo/fabric-seasons-extras). The calendar item has been remade, the texture is now dynamic, and you can place it on a wall.
