### ISSUE TITLE
Silk Touch doesn't work on Greenhouse Glass

### ISSUE THREAD

**Issue by FumpleWumper** [lucaargolo/fabric-seasons#91]
With the mod installed, Silk Touch pickaxes can mine glass as normal, but it doesn't seem to work on Greenhouse Glass, which becomes very inconvenient for building

**Comment by lucaargolo** [comment]
As of version 2.0, all items and blocks have been moved to [Fabric Seasons: Extras](https://github.com/lucaargolo/fabric-seasons-extras). This has also been fixed.
