### ISSUE TITLE
Twilight forest compatibility

### ISSUE THREAD

**Issue by Frontear** [lucaargolo/fabric-seasons#92]
Currently, theres a large biome within the twilight forest made of ice that melts rapidly due to fabric seasons. This can cause a lot of lag. For that I have two proposals

1) Allow dimensions to be disabled from fabric-seasons affecting them, this could prevent it from affecting the twilight forest

2) Add compatibility for the ice queen biome, preventing the ice from melting and causing tons of lag (this isn't really a world-wide fix since any other mods that introduce ice biomes and the like will be affected)

**Comment by muon-rw** [comment]
Twilight Forest likely has the wrong biome temperature value for its Glacier biome. It's 0.8, and was probably meant to be 0.08 (The surrounding forest is 0.09). 

Fabric Seasons makes ice blocks melt at biome temperatures above 0.15.

Correcting the Glacier biome temperature value with a datapack fixes the incompat
