### ISSUE TITLE
FATAL Java Runtime Environment

### ISSUE THREAD

**Issue by zndrmn** [lucaargolo/fabric-seasons#93]
I have the JRE logs but idk if they have any sensitive info in them and I really don't want to skim through it to know so.
If it's really needed and is ok to send, then I will.

[latest.log](https://gist.github.com/zndrmn/ab7d5c5686d3b8251d09edb25b17fc38#file-latest-log)

**Comment by lucaargolo** [comment]
Closing this since it doesn't contain enough info in the log and the mod code changed a lot since it was reported.
