### ISSUE TITLE
Purple leaves with Terralith in 1.19.2

### ISSUE THREAD

**Issue by MastroLupo** [lucaargolo/fabric-seasons#96]
I use this mod with Terralith that add custom leaves color, somo of them are orange and they appear as they should in summer and spring, however in winter and fall they appear purple
![2023-01-18_12 49 43](https://user-images.githubusercontent.com/123004102/213240239-42f4af98-6def-41ec-ae78-bd4eeca9328a.png)
![2023-01-18_12 49 37](https://user-images.githubusercontent.com/123004102/213240252-23e5524a-3baf-4044-ad40-5b3fc6946a4e.png)

**Comment by JairusSW** [comment]
It looks epic, imo. Keep it

**Comment by K3yad** [comment]
happens to me on 1.18.2 as well

**Comment by lucaargolo** [comment]
Heyy. As of version 2.0 all colormaps have been remade. Also I'm currently working on custom compatibility packs for biome mods so that shouldn't be an issues anymore. Here's the compatibility pack for Terralith: https://github.com/lucaargolo/fabric-seasons-terralith-compat
