### ISSUE TITLE
Sleeping doesn't skip the night!

### ISSUE THREAD

**Issue by Cha0sPudd1ng** [lucaargolo/fabric-seasons#98]
If you sleep in the bed, the night get not skipped.

Fabric 1.19.2 (0.14.12)
fabric-seasons-1.4-BETA+1.19

**Comment by DiogoGuedes0305** [comment]
How did you solved it ?

**Comment by lucaargolo** [comment]
Hey, couldn't reproduce this issue in the latest update, so it was probably bein caused by another mod. If this issue still persists in version 2.0, feel free to reopen this issue.
